extends: substitution
message: "Use '%s' instead of '%s'."
link: "https://developers.google.com/style/word-list"
level: warning
ignorecase: false
action:
    name: replace
swap:
    "(?:back-end|back ?end)": backend
    "(?:cell ?phone|smart ?phone)": phone|mobile phone
    "(?:e-mail|Email|E-mail)": email
    "(?:file ?path|path ?name)": path
    "(?:kill|terminate|abort)": stop|exit|cancel|end
    "(?:lastmile|last-mile)": last mile
    "(?:WiFi|wifi)": Wi-Fi
    "(?:unarchive|uncompress|unzip)": extract
    '[\.]+apk': APK
    '3\-D': 3D
    "tap (?:&|and) hold": touch & hold
    "un(?:check|select)": clear
    above: preceding
    account name: username
    action bar: app bar
    admin: administrator
    Ajax: AJAX
    android: Android
    application: app
    approx\.: approximately
    audio capture: audio sample
    audio sampling rate: audio sample rate
    autoupdate: automatically update
    BETA: beta
    bit rate: bitrate
    boolean: Boolean
    bluetooth: Bluetooth
    cellular data: mobile data
    cellular network: mobile network
    chapter: documents|pages|sections
    check box: checkbox
    check: select
    CLI: command-line tool
    click on: click|click in
    curated roles: predefined roles
    data are: data is
    demonstrate: show
    disabled?: turn off|off
    dual streams: dual stream
    fewer data: less data
    file name: filename
    firewalls: firewall rules
    functionality: capability|feature
    Googling: search with Google
    grayed-out: unavailable
    H5: HTML5
    HTTPs: HTTPS
    in order to: to
    ingest: import|load
    Internet: internet
    enter a channel: join a channel
    k8s: Kubernetes
    long press: touch & hold
    multi-channel: multichannel
    multi-media: multimedia
    multi-threaded: multithreaded
    no.: number
    open-source: open source
    regex: regular expression
    re-integrate: reintegrate
    SHA1: SHA-1|HAS-SHA1
    sign into: sign in to
    sign-?on: single sign-on
    stylesheet: style sheet
    synch: sync
    tablename: table name
    tablet: device
    the dual-stream mode: dual-stream mode
    This article: This page
    this article: this page
    touch: tap
    uid: user ID
    url: URL
    uri: URI
    user name: username
    video capturing: video capture
    vs\.: versus
    World Wide Web: web
    wrong: incorrect
