# This workflow will use OxygenScript to build features.

name: Awesome OxygenScript for DITA doc building

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: DITA doc building
      run: |
          cd scripts/oxygen/scripts

          ./transform.sh -i ../../../dita/RTC-NG/RTC_NG_API_CPP.ditamap -sn "DITA Map HTML5 - NG CPP" -s ../../../dita/rtc_api.xpr -v
          ./transform.sh -i ../../../en-US/dita/RTC-NG/RTC_NG_API_CPP.ditamap -sn "DITA Map HTML5 - NG CPP" -s ../../../dita/rtc_api.xpr -v
          ./transform.sh -i ../../../dita/RTC-NG/RTC_NG_API_iOS.ditamap -sn "DITA Map HTML5 - NG iOS" -s ../../../dita/rtc_api.xpr -v
          ./transform.sh -i ../../../en-US/dita/RTC-NG/RTC_NG_API_iOS.ditamap -sn "DITA Map HTML5 - NG iOS" -s ../../../dita/rtc_api.xpr -v
          ./transform.sh -i ../../../dita/RTC-NG/RTC_NG_API_macOS.ditamap -sn "DITA Map HTML5 - NG macOS" -s ../../../dita/rtc_api.xpr -v
          ./transform.sh -i ../../../en-US/dita/RTC-NG/RTC_NG_API_macOS.ditamap -sn "DITA Map HTML5 - NG macOS" -s ../../../dita/rtc_api.xpr -v
          ./transform.sh -i ../../../dita/RTC/RTC_API_CS.ditamap -sn "DITA Map HTML5 - C#" -s ../../../dita/rtc_api.xpr -v
          ./transform.sh -i ../../../en-US/dita/RTC/RTC_API_CS.ditamap -sn "DITA Map HTML5 - C#" -s ../../../dita/rtc_api.xpr -v
