# This workflow will use OxygenScript to build features.

name: Awesome OxygenScript for DITA doc building

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: DITA doc building
      run: |
          cd scripts/oxygen/scripts
          ./batchFormatAndIndent.sh -i ../../../dita -f *.dita -r -ih -v
          ./batchFormatAndIndent.sh -i ../../../en-US/dita -f *.dita -r -ih -v
          ./transform.sh -i ../../../dita -sn -s
          transform.sh -i ../../../dita -sn "DITA Map HTML5 - NG iOS" -s rtc_api.xpr -v
          transform.sh -i ../../../en-US/dita -sn "DITA Map HTML5 - NG iOS" -s rtc_api.xpr -v
          transform.sh -i ../../../dita -sn "DITA Map HTML5 - NG macOS" -s rtc_api.xpr -v
          transform.sh -i ../../../en-US/dita -sn "DITA Map HTML5 - NG macOS" -s rtc_api.xpr -v
          transform.sh -i ../../../dita -sn "DITA Map HTML5 - C#" -s rtc_api.xpr -v
          transform.sh -i ../../../en-US/dita -sn "DITA Map HTML5 - C#" -s rtc_api.xpr -v
          transform.sh -i ../../../dita -sn "DITA Map HTML5 - NG CPP" -s rtc_api.xpr -v
          transform.sh -i ../../../en-US/dita -sn "DITA Map HTML5 - NG CPP" -s rtc_api.xpr -v
          
          transform.sh -i ../../../dita -sn "DITA Map HTML5 - CPP" -s rtc_api.xpr -v
          transform.sh -i ../../../en-US/dita -sn "DITA Map HTML5 - CPP" -s rtc_api.xpr -v
