# This workflow will use OxygenScript to build features.

name: Awesome OxygenScript for DITA doc building

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: montudor/action-zip@v1
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8.0.332+9'
        distribution: 'temurin'
    - name: DITA doc building
      run: |
          cd scripts/oxygen/scripts

          ./transform.sh -i ../../../dita/RTC-NG/RTC_NG_API_CPP.ditamap -sn "DITA Map HTML5 - NG C++" -s ../../../.github/workflows/exported_scenarios.scenarios -v  
    - name: zip files
      run: |
          cd dita/RTC-NG/out
          zip -qq -r cpp_ng.zip "c++ ng"
    - name: Upload C++ NG doc to release
      uses: svenstaro/upload-release-action@v2
      with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dita/RTC-NG/out/cpp_ng.zip
          asset_name: cpp_ng.zip
          tag: main
          overwrite: true
          body: "Template file for automatic comment population."
