# This workflow will use OxygenScript to build features.

name: Awesome OxygenScript for DITA wellformedness check

on: [pull_request]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: DITA wellformedness check
      run: |
          cd scripts/oxygen/scripts
          ./validateCheckDITA.sh -i ../../../dita/rtc_api.xpr -r ditaValidationReport_cn.xml
          
          if [ $? -eq 0 ]
            then
              echo "Validation successful for cn DITA files"
              exit 0
            else
              echo "Validation failure for cn DITA files"
              echo ditaValidationReport_cn.xml
              exit 1
          fi
          
          ./validateCheckDITA.sh -i ../../../en-US/dita/rtc_api.xpr -r ditaValidationReport_en.xml
 
          if [ $? -eq 0 ]
            then
              echo "Validation successful for en DITA files"
              exit 0
            else
              echo "Validation failure for en DITA files"
              echo ditaValidationReport_en.xml
              exit 1
          fi
