# This workflow will use OxygenScript to build features.

name: Awesome OxygenScript for DITA wellformedness check

on: [pull_request]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: DITA wellformedness check
      run: |
          cd scripts/oxygen/scripts
          ./validateCheckDITA.sh -i ../../../dita -r scripts/ditaValidationReport_cn.xml
          ./validateCheckDITA.sh -i ../../../en-US/dita -r scripts/ditaValidationReport_en.xml
    - name: Upload cn validation report to release
      uses: svenstaro/upload-release-action@v2
      with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: scripts/ditaValidationReport_cn.xml
          asset_name: ditaValidationReport_cn
          tag: main
          overwrite: true
          body: "Comment release"
    - name: Upload en validation report to release
      uses: svenstaro/upload-release-action@v2
      with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: scripts/ditaValidationReport_en.xml
          asset_name: ditaValidationReport_en
          tag: main
          overwrite: true
          body: "Comment release"          
