# This workflow will use OxygenScript to build features.

name: Awesome OxygenScript for DITA doc building (FC)

on:
  push:
    branches: [ 'release/flexible-classroom/2.7.0' ]
    # branches: [ master ]

  pull_request:
    # branches: [ 'release/rtc/3.6.2-all' ]
    branches: [ 'release/flexible-classroom/2.7.0' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: montudor/action-zip@v1
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8.0.332+9'
        distribution: 'temurin'
    - name: DITA doc building
      run: |
          cd scripts/oxygen/scripts

          echo "Start building documentation for FC EN iOS"
          echo "-----------------------------------------------------------------------------------------------"
          echo "-----------------------------------------------------------------------------------------------"
          ./transform.sh -i ../../../en-US/dita/flexible-classroom/edu-context/Edu_Context_API_iOS.ditamap -sn "DITA Map HTML5 - FlexibleiOS" -s ../../../.github/workflows/fcr-en-transformation.scenarios -v

    - name: zip files
      run: |
          cd en-US/dita/flexible-classroom/edu-context/out
          ls
          zip -qq -r fc-ios-en-doc.zip "ios-html5"
          ls

    - name: Upload FC EN iOS doc to release
      uses: svenstaro/upload-release-action@v2
      with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: en-US/dita/flexible-classroom/edu-context/out/fc-ios-en-doc.zip
          asset_name: fc-ios-en-doc.zip
          tag: main
          overwrite: true
          body: "DITA docs."
