# GitHub CI build pipeline
name: Awesome JSON CI build for NG Flutter SDK

on:
    push:
        branches:
            - 'master'
    pull_request:
        branches:
            - 'master'
jobs:
    build:
        if: ${{ false }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up python 3.8
              uses: actions/setup-python@v4
              with:
                  python-version: '3.8'
            - name: Get branch name
              id: branch-name
              uses: tj-actions/branch-names@v7
            - name: Install dependencies
              run: |
                  cd xml2json
                  python -m pip install --upgrade pip
                  if  [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - name: Run CN json creation
              run: |
                  cd xml2json
                  echo "Running for flutter NG"
                  python xml2json.py --working_dir ../dita/RTC-NG --platform_tag flutter --json_file flutter_cn_ng.json --sdk_type rtc-ng --remove_sdk_type rtc --defined_path flutter-ng
            - name: Run EN json creation
              run: |
                  cd xml2json
                  echo "Running for flutter NG"
                  python xml2json.py --working_dir ../en-US/dita/RTC-NG --platform_tag flutter --json_file flutter_en_ng.json --sdk_type rtc-ng --remove_sdk_type rtc --defined_path flutter-ng
            - name: Upload CN Artifact
              uses: actions/upload-artifact@v3
              with:
                name: flutter_ng_json_template_cn.json
                path: xml2json/flutter_cn_ng.json
            - name: Upload EN Artifact
              uses: actions/upload-artifact@v3
              with:
                name: flutter_ng_json_template_en.json
                path: xml2json/flutter_en_ng.json
            - name: Upload Flutter NG CN JSON to release
              if: github.ref == github.event.repository.default_branch
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: xml2json/flutter_cn_ng.json
                  asset_name: flutter_ng_json_template_cn.json
                  tag: ${{ steps.branch-name.outputs.current_branch }}
                  overwrite: true
                  body: "Template file for automatic comment population."
            - name: Upload Flutter NG EN JSON to release
              if: github.ref == github.event.repository.default_branch
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: xml2json/flutter_en_ng.json
                  asset_name: flutter_ng_json_template_en.json
                  tag: ${{ steps.branch-name.outputs.current_branch }}
                  overwrite: true
                  body: "Template file for automatic comment population."
        
