# GitHub CI build pipeline
name: Awesome prototype syncs

on:
  pull_request:
    branches:
      - master
      - main
  push:
    branches:
      - master
      - main    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        cd xml2json
        python -m pip install --upgrade pip
        pip install coverage
        if  [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: sync proto type (cn to en)
      run: |
         cd xml2json
         python sync_prototype.py --src_dir ../dita/RTC/API  --dest_dir ../en-US/dita/RTC/API
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
         token: ${{ secrets.GITHUB_TOKEN }}
         commit-message: Sync en prototype
         title: '[Auto] Sync en prototype'
         branch-suffix: short-commit-hash
         body: >
            This PR is auto-generated by 
            [create-pull-request](https://github.com/peter-evans/create-pull-request).
         labels: report, automated pr
