# GitHub CI build pipeline
name: Awesome JSON CI build

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up python 3.8
              uses: actions/setup-python@v4
              with:
                  python-version: '3.8'
            - name: Get branch name
              id: branch-name
              uses: tj-actions/branch-names@v7
            - name: Install dependencies
              run: |
                  cd xml2json
                  python -m pip install --upgrade pip
                  if  [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - name: Run json creation
              run: |
                  cd xml2json
                  echo "Running for Flutter CG"
                  python xml2json.py --working_dir ../en-US/dita/RTC --platform_tag flutter --json_file flutter_newer.json --sdk_type sdk --remove_sdk_type sdk-ng --defined_path flutter
                  # echo "Running for CPP NG"
                  # python xml2json.py --working_dir ../en-US/dita/RTC-NG --platform_tag cpp --json_file cpp_ng.json --sdk_type rtc-ng --remove_sdk_type rtc --defined_path cpp-ng
                  echo "Running for CS CG"
                  python xml2json.py --working_dir ../en-US/dita/RTC --platform_tag cs --json_file csharp_cg.json --sdk_type rtc --remove_sdk_type rtc-ng --defined_path cs
                  # echo "Running for unity NG CN (test)"
                  # python xml2json.py --working_dir ../dita/RTC-NG --platform_tag unity --json_file unity_ng.json --sdk_type rtc-ng --remove_sdk_type rtc --defined_path unity-ng
                  echo "Running for iOS"
                  python xml2json.py --working_dir ../en-US/dita/RTC-NG --platform_tag ios --json_file ios_ng_en.json --sdk_type rtc-ng --remove_sdk_type rtc --defined_path ios
                  python xml2json.py --working_dir ../dita/RTC-NG --platform_tag ios --json_file ios_ng_cn.json --sdk_type rtc-ng --remove_sdk_type rtc --defined_path ios
                  echo "Running for macOS"
                  python xml2json.py --working_dir ../en-US/dita/RTC-NG --platform_tag macos --json_file macos_ng_en.json --sdk_type rtc-ng --remove_sdk_type rtc --defined_path macos
                  python xml2json.py --working_dir ../dita/RTC-NG --platform_tag macos --json_file macos_ng_cn.json --sdk_type rtc-ng --remove_sdk_type rtc --defined_path macos
            - name: Upload Flutter CG JSON to release
              uses: svenstaro/upload-release-action@2.5.0
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: xml2json/flutter_newer.json
                  asset_name: flutter_doc_template.json
                  tag: ${{ steps.branch-name.outputs.current_branch }}
                  overwrite: true
                  body: "Template file for automatic comment population."
            - name: Upload CS CG JSON to release
              uses: svenstaro/upload-release-action@2.5.0
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: xml2json/csharp_cg.json
                  asset_name: csharp_cg_doc_template.json
                  tag: ${{ steps.branch-name.outputs.current_branch }}
                  overwrite: true
                  body: "Template file for automatic comment population."
            - name: Upload iOS JSON to release
              uses: svenstaro/upload-release-action@2.5.0
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: xml2json/ios_ng_en.json
                  asset_name: ios_en_ng_doc_template.json
                  tag: ${{ steps.branch-name.outputs.current_branch }}
                  overwrite: true
                  body: "Template file for automatic comment population."
            - name: Upload macOS JSON to release
              uses: svenstaro/upload-release-action@2.5.0
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: xml2json/macos_ng_en.json
                  asset_name: macos_ng_en_doc_template.json
                  tag: ${{ steps.branch-name.outputs.current_branch }}
                  overwrite: true
                  body: "Template file for automatic comment population."
