name: Linting
on: [push]

jobs:
    prose:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: DITA-OT
              uses: dita-ot/dita-ot-action@master
              with:
                  dita-ot-version: 3.6

            - name: Vale
              uses: errata-ai/vale-action@v1.4.3
              with:
                  # Only lint the modified files
                  # files: __onlyModified
                  # Only lint EN files
                  files: en-US/

                  # Optional
                  config: https://raw.githubusercontent.com/errata-ai/vale/master/.vale.ini

              env:
                  # Required, set by GitHub actions automatically:
                  # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
